name:                haskell-pebble
version:             0.1.0.0
github:              "easafe/haskell-pebble"
license:             MIT
author:              "Eduardo Asafe"
maintainer:          "e@asafe.dev"
copyright:           "2021 Eduardo Asafe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/easafe/haskell-pebble#readme>

dependencies:
- base >= 4.7 && < 5
- text
- optparse-applicative
- load-env
- hashable
- postgresql-simple
- casing
- unordered-containers
- directory

library:
  source-dirs: src

executables:
  haskell-pebble-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-pebble

tests:
  haskell-pebble-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-pebble
    - hspec
