on:
  pull_request:
  push:
    branches: [main]

name: CI

jobs:
  stack:
    runs-on: ${{ matrix.os }}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: pebble
          POSTGRES_PASSWORD: pebble
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      matrix:
        ghc: ['8.10']
        cabal: [latest]
        os: [ubuntu-latest] # , macOS-latest, windows-latest]
    name: CI ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: true
          stack-version: 'latest'
      - uses: actions/cache@v2.1.3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
      - run: psql -f test/sql/index.sql postgresql://pebble:pebble@localhost:5432/pebble
      - name: Install dependencies
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
      - name: Test
        run: |
          stack test --system-ghc
